/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA1_H_RPCGEN
#define _TEMA1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SensorData {
	int dataId;
	int noValues;
	float *values;
};
typedef struct SensorData SensorData;

struct input_login {
	char *name;
};
typedef struct input_login input_login;

struct input_id {
	int id;
};
typedef struct input_id input_id;

struct output_getstat {
	int min;
	int max;
	int average;
	int median;
};
typedef struct output_getstat output_getstat;

#define TEMA1_PROG 0x13112021
#define TEMA1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOAD 1
extern  int * load_1(struct SensorData *, CLIENT *);
extern  int * load_1_svc(struct SensorData *, struct svc_req *);
extern int tema1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOAD 1
extern  int * load_1();
extern  int * load_1_svc();
extern int tema1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SensorData (XDR *, struct SensorData*);
extern  bool_t xdr_input_login (XDR *, input_login*);
extern  bool_t xdr_input_id (XDR *, input_id*);
extern  bool_t xdr_output_getstat (XDR *, output_getstat*);

#else /* K&R C */
extern bool_t xdr_SensorData ();
extern bool_t xdr_input_login ();
extern bool_t xdr_input_id ();
extern bool_t xdr_output_getstat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA1_H_RPCGEN */
