/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHECK_H_RPCGEN
#define _CHECK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct stud {
	char *nume;
	char *grupa;
};
typedef struct stud stud;

#define CHECKPROG_PROG 0x31234567
#define CHECKVERS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GRADE 1
extern  char ** grade_1(struct stud *, CLIENT *);
extern  char ** grade_1_svc(struct stud *, struct svc_req *);
extern int checkprog_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GRADE 1
extern  char ** grade_1();
extern  char ** grade_1_svc();
extern int checkprog_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_stud (XDR *, stud*);

#else /* K&R C */
extern bool_t xdr_stud ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHECK_H_RPCGEN */
