/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema1.hpp"
#include <iostream>
#include <string.h>
#include <fstream>
#include <iterator>
#include <algorithm>
#include <sstream>
#include <cfloat>

using namespace std;

struct input {
	char *command;
};
typedef struct input input;

u_long *session_key;
string name;
bool logged = false;

void
tema1_prog_1(char *host)
{
	CLIENT *clnt;
	session_key = NULL;
	// int  *result_7;
	// struct input_add  update_1_arg;
	// output_getstat_all  *result_10;
	// struct input_key  get_stat_all_1_arg;
	// output_store  *result_11;
	// struct input_key  read_all_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TEMA1_PROG, TEMA1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while(1) {
		string command;
		cin>>command;

		input* client_request = (input*) malloc (sizeof(input));
		client_request->command = (char *) malloc((strlen(command.c_str())+1)*sizeof(char));
        strcpy(client_request->command, command.c_str());

        if (strcmp(client_request->command, "EXIT") == 0 || strcmp(client_request->command, "exit") == 0) {
            printf("Now exiting...\n");
            break;
        }

		if (strcmp(client_request->command, "LOGIN") == 0 || strcmp(client_request->command, "login") == 0) {
			cin>>name;

			struct input_login login_1_arg;
			login_1_arg.name = (char *) malloc(strlen(name.c_str()+1)*sizeof(char));
			strcpy(login_1_arg.name, name.c_str());
			session_key = login_1(&login_1_arg, clnt);
			if (session_key == (u_long *) NULL) {
				clnt_perror (clnt, "call failed at LOGIN");
			} else if (*session_key == 1) {
				cout<<"Client already logged!\n";
			}
			cout<<*session_key<<endl;
			logged = true;
		}

		if (strcmp(client_request->command, "LOGOUT") == 0 || strcmp(client_request->command, "logout") == 0) {
			int *res;
			struct input_key  logout_1_arg;
			if (session_key != NULL) {
				logout_1_arg.session_key = *session_key;
			} else {
				logout_1_arg.session_key = 0;
			}

			res = logout_1(&logout_1_arg, clnt);
			if (res == (int *) NULL) {
				clnt_perror (clnt, "call failed at LOGOUT");
			} else if (*res == 2) {
				cout<<"Client disconected\n";
			} else if (*res == 1) {
				cout<<"Client already logged! You can't logout if you are not logged in!\n";
			} else {
				cout<<"Server had trouble logging you out! Please try again.\n";
			}
		}

		if (strcmp(client_request->command, "LOAD") == 0 || strcmp(client_request->command, "load") == 0) {
			int  *res;
			struct input_load load_1_arg;
			fstream newfile;
			newfile.open(name + ".rpcdb", ios::in);
			if (newfile.is_open()) {
				unsigned line_count = std::count(std::istreambuf_iterator<char>(newfile), std::istreambuf_iterator<char>(), '\n');

				newfile.seekg(0, std::ios::beg);
				
				load_1_arg.nrOfData = line_count+1;
				if (session_key != NULL) {
					load_1_arg.session_key = *session_key;
				} else {
					load_1_arg.session_key = 0;
				}
				load_1_arg.data.data_len = line_count+1;
				load_1_arg.data.data_val = (SensorData *) malloc((line_count+1)*sizeof(SensorData));
				int i = 0;
				string line;

				while(getline(newfile, line)){
					cout<<line<<endl;
					std::stringstream test(line);
					std::string segment;

					std::getline(test, segment, ' ');
					load_1_arg.data.data_val[i].dataId = stoi(segment);
					std::getline(test, segment, ' ');
					load_1_arg.data.data_val[i].noValues = stoi(segment);
					load_1_arg.data.data_val[i].values.values_len = load_1_arg.data.data_val[i].noValues;
					load_1_arg.data.data_val[i].values.values_val = (float *) malloc(load_1_arg.data.data_val[i].noValues * sizeof(float));

					for (int j = 0; j < load_1_arg.data.data_val[i].noValues; j++) {
						std::getline(test, segment, ' ');
						load_1_arg.data.data_val[i].values.values_val[j] = std::stof(segment);
						cout<<i<<" "<<j<<" "<<load_1_arg.data.data_val[i].values.values_val[j]<<endl;
					}

					i++;
				}
				newfile.close();
			}

			res = load_1(&load_1_arg, clnt);
			if (res == (int *) NULL) {
				clnt_perror (clnt, "call failed in LOAD");
			} else if (*res == 1) {
				cout<<"You can't LOAD if you are not logged in!\n";
			} else if (*res == 3) {
				cout<<"You can't LOAD if you made ADD before this LOAD! STORE your session first!\n";
			}
		}

		if (strcmp(client_request->command, "STORE") == 0 || strcmp(client_request->command, "store") == 0) {
			output_store  *res;
			struct input_key store_1_arg;
			if (session_key != NULL) {
				store_1_arg.session_key = *session_key;
			} else {
				store_1_arg.session_key = 0;
			}

			res = store_1(&store_1_arg, clnt);
			cout<<res->nrOfData<<" "<<res->data.data_len<<endl;
			if (res == (output_store *) NULL) {
				clnt_perror (clnt, "call failed");
			} else if (res->nrOfData == -2) {
				cout<<"You can't STORE if you are not logged in!\n";
			} else if (res->nrOfData == 0) {
				fstream file;
				file.open (name + ".rpcdb", ios::out | ios::trunc );
				if (file.is_open()) {
					file.close();
				}
				cout<<"File saved!\n";
			} else {
				fstream file;
				file.open (name + ".rpcdb", ios::out | ios::trunc );
				if (file.is_open()) {
					for (int i = 0; i < res->nrOfData; ++i) {
						file << res->data.data_val[i].dataId;
						file<< " "<< res->data.data_val[i].noValues;
						for (int j = 0; j < res->data.data_val[i].noValues; ++j) {
							file<< " " << res->data.data_val[i].values.values_val[j];
						}
						if (i != res->nrOfData - 1) file << "\n";
					}
					file.close();
				}
				cout<<"File saved!\n";
			}
		}

		if (strcmp(client_request->command, "ADD") == 0 || strcmp(client_request->command, "add") == 0) {
			struct input_add add_1_arg;
			if (session_key != NULL) {
				add_1_arg.session_key = *session_key;
			} else {
				add_1_arg.session_key = 0;
			}
			int *res;
			cin>>add_1_arg.data.dataId>>add_1_arg.data.noValues;
			add_1_arg.data.values.values_len = add_1_arg.data.noValues;
			add_1_arg.data.values.values_val = (float *) malloc(add_1_arg.data.noValues*sizeof(float));
			for (int i = 0; i < add_1_arg.data.noValues; i++) {
				cin>>add_1_arg.data.values.values_val[i];
			}
			res = add_1(&add_1_arg, clnt);
			if (res == (int *) NULL) {
				clnt_perror (clnt, "call failed on ADD");
			} else if (*res == 1) {
				cout<<"You can't ADD if you are not logged in!\n";
			} else if (*res == 3) {
				cout<<"Error: The valueId is already in db!\n";
			} else if (*res == 2) {
				cout<<"Values added!\n";
			}
		}

		if (strcmp(client_request->command, "DEL") == 0 || strcmp(client_request->command, "del") == 0) {
			struct input_id  del_1_arg;
			if (session_key != NULL) {
				del_1_arg.session_key = *session_key;
			} else {
				del_1_arg.session_key = 0;
			}
			int *res;
			cin>>del_1_arg.id;
			res = del_1(&del_1_arg, clnt);
			if (res == (int *) NULL) {
				clnt_perror (clnt, "call failed on DEL");
			} else if (*res == 1) {
				cout<<"You can't DEL if you are not logged in!\n";
			} else if (*res == 3) {
				cout<<"Error: You don't have anything in db!\n";
			} else if (*res == 4) {
				cout<<"Error: The Id is not in db!\n";
			} else {
				cout<<"Item deleted!\n";
			}
		}

		if (strcmp(client_request->command, "UPDATE") == 0 || strcmp(client_request->command, "update") == 0) {
			struct input_add update_1_arg;
			int *res;
			if (session_key != NULL) {
				update_1_arg.session_key = *session_key;
			} else {
				update_1_arg.session_key = 0;
			}

			cin>>update_1_arg.data.dataId;
			cin>>update_1_arg.data.noValues;
			// update_1_arg.data.values.values_len = update_1_arg.data.noValues;
			// update_1_arg.data.values.values_val = (float *) malloc(update_1_arg.data.noValues*sizeof(float));
			// for (int i = 0; i < update_1_arg.data.noValues; ++i) {
			// 	cin>>update_1_arg.data.values.values_val[i];
			// }

			cout<<"DA\n";

			res = update_1(&update_1_arg, clnt);

			if (res == (int *) NULL) {
				clnt_perror (clnt, "call failed on DEL");
			} else if (*res == 1) {
				cout<<"You can't UPDATE if you are not logged in!\n";
			} else if (*res == 3) {
				cout<<"You added a new item to db!\n";
			} else if (*res == 2) {
				cout<<"You added a new item to a new db!\n";
			} else {
				cout<<"Item updated!\n";
			}
		}

		if (strcmp(client_request->command, "READ") == 0 || strcmp(client_request->command, "read") == 0) {
			SensorData  *res;
			struct input_id  read_1_arg;

			cin>>read_1_arg.id;

			if (session_key != NULL) {
				read_1_arg.session_key = *session_key;
			} else {
				read_1_arg.session_key = 0;
			}

			res = read_1(&read_1_arg, clnt);
			if (res == (SensorData *) NULL) {
				clnt_perror (clnt, "call failed");
			} else if (res->dataId == 1 && res->noValues == 0) {
				cout<<"You can't READ if you are not logged in!\n";
			} else if (res->dataId == 0 && res->noValues == 0) {
				cout<<"You don't have any items!\n";
			}  else if (res->dataId == 3 && res->noValues == 0) {
				cout<<"You don't have this item!\n";
			} else {
				cout<<res->dataId<<" "<<res->noValues;
				for (int i = 0; i < res->noValues; ++i) {
					cout<<" "<<res->values.values_val[i];
				}
				cout<<endl;
			}
		}

		if (strcmp(client_request->command, "GET_STAT") == 0 || strcmp(client_request->command, "get_stat") == 0) {
			output_getstat  *res;
			struct input_id  get_stat_1_arg;

			cin>>get_stat_1_arg.id;

			if (session_key != NULL) {
				get_stat_1_arg.session_key = *session_key;
			} else {
				get_stat_1_arg.session_key = 0;
			}

			res = get_stat_1(&get_stat_1_arg, clnt);
			if (res == (output_getstat *) NULL) {
				clnt_perror (clnt, "call failed");
			} else if (res->min == 0 && res->max == FLT_MAX) {
				cout<<"You can't GET_STAT if you are not logged in!\n";
			} else if (res->min == FLT_MAX && res->max == 0) {
				cout<<"You don't have any items!\n";
			}  else if (res->min == FLT_MAX && res->max == FLT_MAX) {
				cout<<"You don't have this item!\n";
			} else {
				cout<<res->min<<" "<<res->max<<" "<<res->average<<" "<<res->median<<endl;
			}
		}
	}

	// result_7 = update_1(&update_1_arg, clnt);
	// if (result_7 == (int *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_9 = get_stat_1(&get_stat_1_arg, clnt);
	// if (result_9 == (output_getstat *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_10 = get_stat_all_1(&get_stat_all_1_arg, clnt);
	// if (result_10 == (output_getstat_all *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tema1_prog_1 (host);
exit (0);
}
